services:
  postgres:
    build:
      args:
       USERNAME: ${USERNAME:?err}
       BUILD_DIR: build/postgres
      context: ./docker
      dockerfile: Dockerfile
    container_name: postgres-master
    hostname: postgres
    image: postgres/development:master
    network_mode: host
    ports:
      - 5432:5432
    restart: always
    tty: true
    user: ${USERNAME:?err}
networks:
  default:
    name: host
